services:
  # # Git server for version control
  # gitserver:
  #   build:
  #     context: .
  #     dockerfile: gitserver.Dockerfile
  #   container_name: git-server
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - git_repos:/home/git
  #   networks:
  #     - react-network

  # Nginx to serve the React app
  nginx:
    image: nginx:alpine
    container_name: react-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - react-network

# volumes:
#   git_repos:

networks:
  react-network:
    driver: bridge
